### ISSUE TITLE
PDF parser not working

### ISSUE THREAD

**Issue by timnugent** [clips/pattern#101]
I tried the PDF download/parsing example here:
http://www.clips.ua.ac.be/pages/pattern-web#pdf

But ran into this issue:

Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > from pattern.web import URL, PDF
> > > url = URL('http://www.clips.ua.ac.be/sites/default/files/ctrs-002_0.pdf')
> > > pdf = PDF(url.download())
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/Pattern-2.6-py2.7.egg/pattern/web/**init**.py", line 3775, in **init**
> > >     self.content = self._parse(path, format=output)
> > >   File "/usr/local/lib/python2.7/dist-packages/Pattern-2.6-py2.7.egg/pattern/web/__init__.py", line 3790, in _parse
> > >     raise PDFError(str(e))
> > > pattern.web.PDFError: must be encoded string without NULL bytes, not str

Using latest version from Git under Ubuntu 14.04.

Cheers,
Tim

**Comment by Abhilash-D** [comment]
Oh. It worked for me after I made unicode=True. No idea what would be the issue then.

**Comment by Leanwit** [comment]
Hi, i get the same problem whit pdf, but the error is the next:
"must be encoded string without NULL bytes, not unicode"
