### ISSUE TITLE
pattern.web.Mail raises MailLoginError with correct credentials

### ISSUE THREAD

**Issue by pedrokoblitz** [clips/pattern#116]
I have double checked username and password. I tried two different accounts. I have made sure IMAP was enabled. But I'm still getting:

``` python
Traceback (most recent call last):
  File "gmail.py", line 6, in <module>
    gmail = Mail(username='username@gmail.com', password='pass', service=GMAIL)
  File "/usr/local/lib/python2.7/dist-packages/pattern/web/imap/__init__.py", line 115, in __init__
    self.login(username, password)
  File "/usr/local/lib/python2.7/dist-packages/pattern/web/imap/__init__.py", line 137, in login
    raise MailLoginError
pattern.web.imap.MailLoginError
```

with the following code:

``` python
#!/usr/bin/python
# -*- coding: utf-8 -*-
from pattern.web import Mail, GMAIL, SUBJECT
gmail = Mail(username='username@gmail.com', password='password', service=GMAIL)
```

**Comment by mcboman** [comment]
Have you tried setting the Secure=False?

This document might help: https://docs.python.org/2/library/imaplib.html

**Comment by pedrokoblitz** [comment]
Thank you. Will try later today.
