### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by darmawiguna** [clips/pattern#209]
I am new in python. What is the error of this while installing?

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/2d/449tr65508b052gjnmbvv3p40000gn/T/pip-build-rp2ndohf/pattern/setup.py", line 40
        print n
              ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int n)?
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/2d/449tr65508b052gjnmbvv3p40000gn/T/pip-build-rp2ndohf/pattern/

**Comment by jatin-practice** [comment]
Looks like you are trying with python 3.x version . you can change the print statement to print (n) or try with python 2.x version

**Comment by darmawiguna** [comment]
I installed using pip install pattern. How to change it to python2 before installing the pattern?

**Comment by jatin-practice** [comment]
Can you try like pip2.7 install pattern

**Comment by darmawiguna** [comment]
Awesome. It worked. Thank you so much.

**Comment by eyb1** [comment]
You can also ```pip install pattern3```, however there is an error in ```pattern3\text\tree.py``` in the pypi package currently (which is why I'm here)...

**Comment by thalelinh** [comment]
Related [#232](https://github.com/clips/pattern/issues/232)
