### ISSUE TITLE
 Command "python setup.py egg_info" failed with error code 1 

### ISSUE THREAD

**Issue by hanuX39** [clips/pattern#279]
Collecting pattern
  Using cached https://files.pythonhosted.org/packages/1e/07/b0e61b6c818ed4b6145fe01d1c341223aa6cfbc3928538ad1f2b890924a3/Pattern-3.6.0.tar.gz
Collecting future (from pattern)
  Using cached https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz
Collecting backports.csv (from pattern)
  Using cached https://files.pythonhosted.org/packages/8e/26/a6bd68f13e0f38fbb643d6e497fc3462be83a0b6c4d43425c78bb51a7291/backports.csv-1.0.7-py2.py3-none-any.whl
Collecting mysqlclient (from pattern)
  Using cached https://files.pythonhosted.org/packages/f4/f1/3bb6f64ca7a429729413e6556b7ba5976df06019a5245a43d36032f1061e/mysqlclient-1.4.2.post1.tar.gz
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-lgocit98/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "/tmp/pip-install-lgocit98/mysqlclient/setup_posix.py", line 51, in get_config
        libs = mysql_config("libs")
      File "/tmp/pip-install-lgocit98/mysqlclient/setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-lgocit98/mysqlclient/

**Comment by pidugusundeep** [comment]
> Collecting pattern
> Using cached https://files.pythonhosted.org/packages/1e/07/b0e61b6c818ed4b6145fe01d1c341223aa6cfbc3928538ad1f2b890924a3/Pattern-3.6.0.tar.gz
> Collecting future (from pattern)
> Using cached https://files.pythonhosted.org/packages/90/52/e20466b85000a181e1e144fd8305caf2cf475e2f9674e797b222f8105f5f/future-0.17.1.tar.gz
> Collecting backports.csv (from pattern)
> Using cached https://files.pythonhosted.org/packages/8e/26/a6bd68f13e0f38fbb643d6e497fc3462be83a0b6c4d43425c78bb51a7291/backports.csv-1.0.7-py2.py3-none-any.whl
> Collecting mysqlclient (from pattern)
> Using cached https://files.pythonhosted.org/packages/f4/f1/3bb6f64ca7a429729413e6556b7ba5976df06019a5245a43d36032f1061e/mysqlclient-1.4.2.post1.tar.gz
> ERROR: Complete output from command python setup.py egg_info:
> ERROR: /bin/sh: mysql_config: command not found
> Traceback (most recent call last):
> File "", line 1, in 
> File "/tmp/pip-install-lgocit98/mysqlclient/setup.py", line 16, in 
> metadata, options = get_config()
> File "/tmp/pip-install-lgocit98/mysqlclient/setup_posix.py", line 51, in get_config
> libs = mysql_config("libs")
> File "/tmp/pip-install-lgocit98/mysqlclient/setup_posix.py", line 29, in mysql_config
> raise EnvironmentError("%s not found" % (_mysql_config_path,))
> OSError: mysql_config not found
> ----------------------------------------
> ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-lgocit98/mysqlclient/

I have the same issue how do I fix this?

**Comment by ansable** [comment]
hi, we are working on the effective solution, but for now you could just follow the solution given here:

https://github.com/clips/pattern/issues/275

if you are not planning to work with the databases whatsoever, you can just go to setup.py and delete the line ""mysqlclient" (on the picture)
![image](https://user-images.githubusercontent.com/30018899/60182157-057f8a80-9824-11e9-85e3-66a301e4ea3b.png)

fixed issue will be merged to master-branch this week!

**Comment by atotalnoob** [comment]
This issue occurs on Google Colabs

```
Collecting pattern
  Using cached https://files.pythonhosted.org/packages/1e/07/b0e61b6c818ed4b6145fe01d1c341223aa6cfbc3928538ad1f2b890924a3/Pattern-3.6.0.tar.gz
Requirement already satisfied: urllib3<1.25,>=1.20 in /usr/local/lib/python3.6/dist-packages (from flair) (1.24.3)
Requirement already satisfied: pytest>=3.6.4 in /usr/local/lib/python3.6/dist-packages (from flair) (3.6.4)
Requirement already satisfied: deprecated>=1.2.4 in /usr/local/lib/python3.6/dist-packages (from flair) (1.2.6)
Requirement already satisfied: sklearn in /usr/local/lib/python3.6/dist-packages (from flair) (0.0)
Requirement already satisfied: hyperopt>=0.1.1 in /usr/local/lib/python3.6/dist-packages (from flair) (0.1.2)
Requirement already satisfied: mpld3==0.3 in /usr/local/lib/python3.6/dist-packages (from flair) (0.3)
Requirement already satisfied: pytorch-transformers>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from flair) (1.2.0)
Requirement already satisfied: gensim>=3.4.0 in /usr/local/lib/python3.6/dist-packages (from flair) (3.6.0)
Requirement already satisfied: segtok>=1.5.7 in /usr/local/lib/python3.6/dist-packages (from flair) (1.5.7)
Requirement already satisfied: bpemb>=0.2.9 in /usr/local/lib/python3.6/dist-packages (from flair) (0.3.0)
Requirement already satisfied: matplotlib>=2.2.3 in /usr/local/lib/python3.6/dist-packages (from flair) (3.0.3)
Requirement already satisfied: sqlitedict>=1.6.0 in /usr/local/lib/python3.6/dist-packages (from flair) (1.6.0)
Requirement already satisfied: langdetect in /usr/local/lib/python3.6/dist-packages (from flair) (1.0.7)
Requirement already satisfied: ipython-genutils==0.2.0 in /usr/local/lib/python3.6/dist-packages (from flair) (0.2.0)
Requirement already satisfied: regex in /usr/local/lib/python3.6/dist-packages (from flair) (2019.8.19)
Requirement already satisfied: tqdm>=4.26.0 in /usr/local/lib/python3.6/dist-packages (from flair) (4.28.1)
Requirement already satisfied: tabulate in /usr/local/lib/python3.6/dist-packages (from flair) (0.8.5)
Requirement already satisfied: ipython==7.6.1 in /usr/local/lib/python3.6/dist-packages (from flair) (7.6.1)
Requirement already satisfied: torch>=1.1.0 in /usr/local/lib/python3.6/dist-packages (from flair) (1.2.0)
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from pattern) (0.16.0)
Collecting backports.csv (from pattern)
  Using cached https://files.pythonhosted.org/packages/8e/26/a6bd68f13e0f38fbb643d6e497fc3462be83a0b6c4d43425c78bb51a7291/backports.csv-1.0.7-py2.py3-none-any.whl
Collecting mysqlclient (from pattern)
  Using cached https://files.pythonhosted.org/packages/4d/38/c5f8bac9c50f3042c8f05615f84206f77f03db79781db841898fde1bb284/mysqlclient-1.4.4.tar.gz
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by sviperm** [comment]
> This issue occurs on Google Colabs

Can confirm issue on google colabs
```
Collecting mysqlclient
Using cached  https://files.pythonhosted.org/packages/d0/97/7326248ac8d5049968bf4ec708a5d3d4806e412a42e74160d7f266a3e03a/mysqlclient-1.4.6.tar.gz
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by naveenjafer** [comment]
Is there a potential fix for this yet? I am using it in google colab and running into the same errors as the above 2 comments

**Comment by Galina-Blokh** [comment]
me too :(

Collecting pattern
  Using cached https://files.pythonhosted.org/packages/1e/07/b0e61b6c818ed4b6145fe01d1c341223aa6cfbc3928538ad1f2b890924a3/Pattern-3.6.0.tar.gz
Requirement already satisfied: future in /usr/local/lib/python3.6/dist-packages (from pattern) (0.16.0)
Collecting backports.csv
  Using cached https://files.pythonhosted.org/packages/8e/26/a6bd68f13e0f38fbb643d6e497fc3462be83a0b6c4d43425c78bb51a7291/backports.csv-1.0.7-py2.py3-none-any.whl
Collecting mysqlclient
  Using cached https://files.pythonhosted.org/packages/3c/df/59cd2fa5e48d0804d213bdcb1acb4d08c403b61c7ff7ed4dd4a6a2deb3f7/mysqlclient-2.0.3.tar.gz
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by fredzannarbor** [comment]
bump
