### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by city-in-the-sky** [clips/pattern#62]
Pattern should start supporting Python 3. Looking at the amount of code, it is a non-trivial task and any help is much appreciated.

**Comment by Zearin** [comment]
+1 for Python 3 support.

I realize the need to support a mature, powerful, and loyal community of legacy Python users, but Python 3 is only going to get more relevant with time, not less.  

More importantly, Python 3 is just **better**.  Its standard library organization is much cleaner, its syntax is more readable, and in many common cases it performs significantly better than Python 2 (speed and/or memory footprint).  

That said, it’s often tricker to port to Python 3 than it “feels” like it should be.  For a while, `six` has helped make this a little easier, but it only went so far.  

To make the transition as painless as possible, I strongly recommend the [**Python-Future**](http://python-future.org/automatic_conversion.html) package. It is **way** more powerful than `six`; it has tools focused on automating as much of the transition as possible; _and_ it has truly excellent documentation.  

I believe it was mentioned earlier in this thread, but I just wanted to reiterate its awesomeness for anyone that might have missed it.  Seriously—just browsing its documentation can evoke the inspiration to transition to a 2-3 compatible codebase.

----

I haven’t used Pattern yet, but it also has excellent documentation (great job!).  Unfortunately, my current research is in Python 3.  That’s how I found my way to this page.  I hope Pattern gets to Python 3 soon!  

Keep up the excellent work, and May The Source™ Be With You!

**Comment by hayd** [comment]
@Zearin I used future to do the majority of the heavy lifting in the python 3 port, see the pattern3 repo. Please do try it out.

**Comment by MarcosGinel** [comment]
How could you define the "state" of the project for porting Pattern into Python 3?

I used two years ago for Python 2.7 and it was awesome, now I'm going to work with Python 3 and I would love to use it (Pattern) again!

Thanks!

**Comment by legel** [comment]
Greetings, we came across this [from here](https://github.com/overlap-ai/words2map/issues/3), and I just noticed that while a lot of the build looks stable, support for Python 3.3 seems not to be working? At least that is how I would interpret the [Travis CI page](https://travis-ci.org/pattern3/pattern). Thanks.

**Comment by legel** [comment]
I just quickly tested it on Python 3.4, by creating a conda virtual environment with python 3.4 (using `conda create -n python3 python=3.4 anaconda`) and running the following:
```
    git clone https://github.com/pattern3/pattern.git
    cd pattern
    python setup.py install
```
However, unfortunately, upon testing, text parsing functions at least for the web module do not seem to work... In the test folder I ran `python test_web.py` which is what we are using, and the following is a sample of what I got back...

```
======================================================================
FAIL: test_plaintext (__main__.TestPlaintext)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_web.py", line 455, in test_plaintext
    u"<a href=\"http://www.domain.com\">link</a>\n\n* item1 xxx\n* item2")
AssertionError: 'tags amp; things\n\ntitle1\n\ntitle2\n\nparagr[93 chars]tem2' != 'tags & things\n\ntitle1\n\ntitle2\n\nparagraph[76 chars]tem2'
- tags amp; things

======================================================================
FAIL: test_encode_utf8 (__main__.TestUnicode)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_web.py", line 53, in test_encode_utf8
    self.assertTrue(isinstance(web.encode_utf8(s), str))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 91 tests in 0.500s

FAILED (failures=4, errors=40, skipped=1)                                       357d  ⍉

(python3)
```

**Comment by davidhorat** [comment]
I used pattern with Python 2 before and I loved it, but now I switched to Python 3. What is the status of porting Pattern to Python 3?

**Comment by jamesacampbell** [comment]
It is astonishing to me that someone hasn't completed a full update to get Python 3 version of pattern working. I guess I will fork pattern3 and try to finish it myself.

**Comment by jamesacampbell** [comment]
never mind. too many recursion errors, encoding errors, etc. someone who knows the actual codebase should really update it.

**Comment by hayd** [comment]
@jamesacampbell it's not so far off https://github.com/pattern3/pattern/issues/5

**Comment by jamesacampbell** [comment]
@hayd yeah i was getting bogged down in all of the failures in test_web and test_db but did notice that the others were passing. commenting in that thread now. thanks

**Comment by fabriciorsf** [comment]
Tips to write Python 2-3 compatible code:
http://python-future.org/compatible_idioms.html
https://docs.python.org/3/howto/pyporting.html

This library is very good, and it can't stop in time...

**Comment by tom-de-smedt** [comment]
Support for Python 3 is a long and ongoing discussion.

@hayd has done a lot of work on this -- see also https://github.com/pattern3/pattern

@hayd and I agreed that we should merge his work back into the main branch and take it step by step in a single branch, but I never get round to it due to time constraints. It's frustrating. Students at the university are now taught Python 3 and we can't offer Pattern to tell them about Natural Language Processing.

I will give it another go by submitting the task to Google Summer of Code.

But really Pattern needs more people that manage pull requests, that have push and admin rights, and that can take it into their own hands. Being the sole admin has worked well in the past to keep the source code clean and the focus tight, but we need to rethink this strategy.

Contact me at tom@organisms.be if you feel like stepping up.

**Comment by pradyunsg** [comment]
@tom-de-smedt I would be interested in taking this on as a part of GSoC.

**Comment by proycon** [comment]
Possibly relevant in this discussion: http://www.python3statement.org/  , major scientific Python projects are phasing out 2.7 support. You might even want to consider dropping 2.7 entirely and switch to 3 at a next major version release, if that makes the transition easier.

**Comment by andela-bolajide** [comment]
Hello everyone, i've gone through the issues and it's very interesting. So many questions asked about `pattern`'s compatibility with Python3. Currently working on a python3 project and i need pattern but i can't install due to compatibility issues.

@hayd i went through your pattern3 repo and noticed the Travis build was failing do you need help with that.

**Comment by jamesacampbell** [comment]
@andela-bolajide can't speak for @hayd but please if you have time fork it and get the travis builds passing and then do a merge request or I would use your fork as is in meantime if you get it fully working in Python 3. I don't have time myself to do it.

**Comment by andela-bolajide** [comment]
Okay @jamesacampbell, i'll get to work tomorrow and i'll be in touch. Cheers man

**Comment by achillesliu** [comment]
Hi guys, I found that textblob is using pattern library and they provide python 3 support. So if anyone is in a hurry, just to there and check the docs.

**Comment by afsun** [comment]
Hi ,
I using python 3, I cant install pattern with anaconda. I try 'pip install pattern',but it doesn't work .
this is the result:
![untitled](https://cloud.githubusercontent.com/assets/26040019/26032989/1da48c52-38b6-11e7-9ff8-c19040e3f488.jpg)

**Comment by andela-bolajide** [comment]
Pattern isn't compatible with Python3 yet. @afsun

**Comment by afsun** [comment]
my friend installed it for python3. but she cant remember how did she do that !

**Comment by pradyunsg** [comment]
> @tom-de-smedt I would be interested in taking this on as a part of GSoC.

I did not take this project.

**Comment by markus-beuckelmann** [comment]
I will work on this issue as part of this year's GSoC, so there will definitely be some substantial progress over the summer. We will probably track most of the development in the preliminary [pattern3](http://github.com/pattern3/pattern) repository for now, since parts of the code are already ported. We'll see what the status quo is – what works and doesn't work – over the next weeks.

So if you want to be part of all that (which would be great!), bring in your ideas or thoughts on the process and make sure to follow the above mentioned repository.

**Comment by jamesacampbell** [comment]
@markus-beuckelmann very excited about this, thanks

**Comment by tom-de-smedt** [comment]
Update: As part of Google Summer of Code 2017, Markus Beuckelmann (@markus-beuckelmann) will be working on the future of Pattern (porting it to Python 3 is first on our list). Markus is admin of the repo now and can handle pull requests and invite collaborators. Be sure to reach out to him and include him in discussions about the port. About the [pattern3](https://github.com/pattern3/pattern) fork: a lot of work was done here by Andy Hayden (@hayd). Andy & I agreed that a fork, which was my idea, was not the best idea. All work on porting the toolkit should happen here. So we will take what we can use from the pattern3 repo, put it in here, and continue here, eventually discarding the pattern3 fork. It is less confusing for everyone if we work on 1 repo instead of 2 forks. Hopefully we can make some progress over the summer.

**Comment by markus-beuckelmann** [comment]
Thanks @tom-de-smedt, I hope it's going to be a productive summer! Here is how I plan to proceed...

- First steps will be...
  - to rip out the bundled dependencies (e.g. `feedparser`, `json`, `BeautifulSoup`, ... in `pattern.web`) from the code base and make them external dependencies. (Done!)
  - to make ideally all unit tests pass for Python 2.7.13. Only from this we can confidently start porting to Python 3 and immediately see if the introduced changes break Python 2 support.
- Unfortunately, as of right now, not all unit tests pass for Python 2.7.13, e.g. a lot of tests in `test_web.py` fail because either APIs are discontinued or deprecated – we can just skip these for now and deal with it later. Others are more important, e.g. in `test_en.py`, `test_text.py` and it's not immediately clear (at least to me) why they fail now when they used to pass. I'll have to look into this...
- I will setup [Travis CI](https://travis-ci.org/clips/pattern/) (continuous integration) to make the unit testing easier, especially to keep track of which tests pass/fail for different Python versions. (Done!)
- I'll leave the `master` branch untouched for now and keep all the commits working towards a stable Python 2.7 version in the `development` branch. Forked from `development` we will have a `python3` branch where we can work on porting to Python 3.
- We will merge `python3` back to `development` later down the line and eventually merge everything back into `master`. If the changes are significant enough, we should at some point consider releasing a new major release.
- I will also try to create something like a todo list listing individual steps of the overall process (both related to porting to Python 3 and more general improvements) and maybe some milestones. Maybe this will make it easier for people to jump in and work on some issues.
- Let's continue to use this issue here ([#62](https://github.com/clips/pattern/issues/62)) to talk about the general status quo and bigger picture of Python 3 support. However, I will open some issues in the next days where we can talk about the details of individual steps/problems.
- One more thing: What are people's thoughts on dropping support for Python 2.6?

Finally, and I think I speak in the name of many Pattern users/developers, special thanks to @hayd for all the valuable work done in the [pattern3](https://github.com/pattern3/pattern) fork. We will make use of it wherever reasonable.

**Comment by xenu256** [comment]
Just checked pattern3 and it seems it also uses sgmllib inside pattern/web, would be good someone is familiar how it works or what it does (maybe code for that lib?) as due to that one I can't even start running tests :) I think it can be changed to lxml. Every other test of pattern3 seems doesn't have such dependencies and can be worked out.

**Comment by markus-beuckelmann** [comment]
I realize I'm a bit behind on keeping people following this issue up to date with the latest progress! Google Summer of Code is over, since a couple weeks now already, and it has brought substantial progress (see full [list of commits](https://github.com/clips/pattern/compare/75f40b7...ec95f97)). We are now in a position where we have a version on the `development` branch that supports all modules except for `pattern.server` on *both* Python 2.7 and Python 3.5+. For people who want to find out more about the specifics and intermediate steps, go ahead and read my detailed GSoC reports on the [Newsaudit](http://www.newsaudit.net/blog) blog ([#1](http://www.newsaudit.net/node/28), [#2](http://www.newsaudit.net/node/46), [#3](http://www.newsaudit.net/node/60)).

So now the plan is to smooth out the rough edges and release a new major version Pattern 3.0 within the next months. There is really only one known bug at the moment that is solely related to Python 3 and it only affects the information gain tree classifier `IGTree` in `pattern.vector`. Then there are a couple of issues like deprecated web APIs in `pattern.web` that should be addressed before the next release.

In the meantime, everybody feel free to check out the `development` branch and report any issues that may come along!

**Comment by transfluxus** [comment]
not sure how long this is gonna take. but as soon as the page is up again maybe you can add some info about that dev works with py3, what the restrictions are (what does not work yet) and how to install it. e.g.
go into your python3 environment!
```
git clone https://github.com/clips/pattern
cd pattern
git fetch
git checkout development
python setup.py install
```
might make a lot of people happy

**Comment by markus-beuckelmann** [comment]
Sure, I will update the `README.md` on the `master` branch with some more information in the next days.

**Comment by jpfairbanks** [comment]
@markus-beuckelmann Is there any update on this? Is the current advice to build the development branch if we need python 3 support?

**Comment by markus-beuckelmann** [comment]
@jpfairbanks, yes, if you need Python 3 support right now you can check out the `development` branch: `git clone -b development https://github.com/clips/pattern`

**Comment by derNarr** [comment]
On debian 9 ``mysql_init`` was missing, while trying to install the development branch of ``pattern`` under python3. After I installed the mariadb drop-in replacement for ``mysql_init`` with ``sudo apt-get install libmariadbclient-dev`` everything I tried worked as expected with the ``pattern`` module.

**Comment by masaguaro** [comment]
I have installed  ```pattern3``` with ```pip``` in a ```conda``` virtual environment.  I am working in ```Windows 8.1  64-bit``` .When I try to execute
 ```from pattern3.en import tag```
I have the following errror:
```
Traceback (most recent call last):
  File "test_pattern.py", line 5, in <module>
    from pattern3.en import tag
  File "C:\Users\Rodolfo\Anaconda3\envs\flasky\lib\site-packages\pattern3\text\en\__init__.py", line 22, in <module>
    from pattern3.text import (
  File "C:\Users\Rodolfo\Anaconda3\envs\flasky\lib\site-packages\pattern3\text\__init__.py", line 28, in <module>
    from pattern3.text.tree import Tree, Text, Sentence, Slice, Chunk, PNPChunk, Chink, Word, table
  File "C:\Users\Rodolfo\Anaconda3\envs\flasky\lib\site-packages\pattern3\text\tree.py", line 37
    except:
         ^
IndentationError: expected an indented block
```
Any idea  or help will be appreciated :)

**Comment by JanmajaySingh** [comment]
@masaguaro I have the same issue while trying to use gensim lemmatization. Maybe a recent push gone wrong by a mix of tabs and spaces?

I'll open a new issue about this.

**Comment by masaguaro** [comment]
Thank you @JanmajaySingh . I posted the same question on _stackoverflow_ but I had no answer . It seems that there is not too much  Python 3 support. Perhaps you are right, and it's just a mix of tabs and spaces, which shouldn't be difficult to fix (using _Sublime_, for example). Right now, I am doing some work with NLPTK, but I will keep your idea for future use.

**Comment by markus-beuckelmann** [comment]
@masaguaro @JanmajaySingh (#217), you are using the deprecated `pattern3` repository which contains a completely different code base that is not maintained anymore. There is a `development` branch here on `clips/pattern` with Python 3 support. You can clone it, `git clone -b development https://github.com/clips/pattern` and install with `pip` or `conda`. Let us know if there are any issues with the `development` branch...

**Comment by JanmajaySingh** [comment]
@markus-beuckelmann Thanks! Issue #217 was closed.

**Comment by masaguaro** [comment]
Hello @markus-beuckelmann  @JanmajaySingh   
 I am working in Windows 8.1 64-bit, in a conda virtual environment.
I was trying to run [pattern/examples/01-web/04-twitter.py](url) and I had the following error: 

```
Traceback (most recent call last):
  File "C:\Users\Desktop\pattern\examples\01-web\04-twitter.py", line 12, in <module>
    from pattern.db import Datasheet, pprint, pd
  File "C:\Users\Desktop\pattern\examples\01-web\..\..\pattern\db\__init__.py", line 1879, in <module>
    csvlib.field_size_limit(sys.maxsize)
OverflowError: Python int too large to convert to C long
[Finished in 1.5s]
```
Any idea ?  Thank you in advance.

**Comment by zedrem** [comment]
Hey,

Is there any time frame on an official release of the python3 support? Or an idea of how close it is to being ready?

Thanks,
Ash

**Comment by tuxayo** [comment]
If enough people are interested, especially if it helps them working. Maybe we can consider putting a bounty on this task? It would be nice if such work would be paid :)
https://www.bountysource.com/issues/1685084-python-3-support
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=1685084)](https://www.bountysource.com/issues/1685084-python-3-support?utm_source=1685084&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by JanmajaySingh** [comment]
@zedrem @tuxayo Considering that the development branch was last updated 9 months ago, I guess the primary contributors have been busy. 

The dev branch in its current form works without issues (at least for me). You can refer to @markus-beuckelmann 's comment (March 6).

**Comment by JanmajaySingh** [comment]
@masaguaro I dunno if you could find a workaround to your issue, but I guess modifying the C source code to something like long long int might help. But it may break other modules in unexpected ways. I don't know any other details about your project though, you're better off asking on S/O.

**Comment by zedrem** [comment]
Yea thanks, I've read the thread and understand that you can use the tool from the development branch. For what I needed, I was happy to even use the pattern3 side-project that was set up initially and then discontinued.

However, I really like patterns article extraction tool and want to incorporate it into another tool that I'm building. As far as i'm aware (?) there is no way to do that with pattern in its current condition. I'm guessing that you can't specify specific git branches in your requirements.txt for example?

If anyone is aware of any similar article extraction tools, please let me know (but I'm conscious that it is off topic for this thread).

**Comment by septiangilang** [comment]
@zedrem For me, I can install it by running this
> sudo apt-get install mysql-server
> sudo apt-get install libmysqlclient-dev
> git clone -b development https://github.com/clips/pattern
> cd pattern/
> sudo python3 setup.py install

**Comment by tom-de-smedt** [comment]
A lot of work was done by @markus-beuckelmann during last year's GSoC. During this year's GSoC, @Xsardas1000 (Maksim Filim) is doing great work (Markus & me are mentoring). Check Max' progress here: https://github.com/clips/pattern/tree/devmodified

We should be able to get out an "overall stable" official release by the end of the month, if everything goes well. 

If you notice things that don't work yet, please report them here. Better yet, if you want to help out, please let us know, we can give you some editing privileges and author credits to move things forward more quickly.

As a side note, the documentation needs to move to a new location too (e.g., www.pattern3.net). Let us know if you'd want to contribute some web development skills to this end.

Thanks for your patience, we're nearing a stable release of Pattern 3.

**Comment by thalelinh** [comment]
Hy, I'm an undergrad student at Unicamp (Brazil) and got interested in helping this repo. I thought about starting with code coverage and found that there's some duplicated code at `server/__init__.py`, `db/__init__.py` and others, is this intentional?
